######################################################################
# Automatically generated by qmake (2.01a) Sat Oct 13 21:39:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Bot.h Insel.h Feld.h Aktion.h
SOURCES += Bot.cpp Insel.cpp Feld.cpp main.cpp
